### ISSUE TITLE
Causes prettier to crash (Error: Cannot find module 'prettier/parser-babel')

### ISSUE THREAD

**Issue by sindre-nistad** [shellscape/prettier-plugin-package#19] opened 2020-11-03 15:23 UTC
- Prettier Version: 2.1.2
- Operating System (or Browser): Ubuntu 18.04.5
- Node Version: 14.15.0
- prettier-plugin-package Version: 1.2.0, 1.1.0

### How Do We Reproduce?

In a [pre-commit hook](https://pre-commit.com), I use prettier, with the prettier-plugin-package.

_.pre-commit-config.yaml_
```
default_language_version:
  python: python3.9

repos:
  - repo: https://github.com/prettier/prettier
    rev: 2.1.2
    hooks:
      - id: prettier
        files: ^.*\.(tsx?|jsx?|s?css|html|json|ya?ml|toml|md)$
        exclude: "web/((tsconfig|public/manifest|.stylelintrc).json)"
        args:
          [
            "--config=.prettier.config.js",
            "--plugin=prettier-plugin-package",
            "--plugin=prettier-plugin-toml",
          ]
        additional_dependencies:
          - prettier-plugin-package@1.1.0
          - prettier-plugin-toml@0.3.1
```

When I remove `prettier-plugin-package`, the hook executes as normal.

### Expected Behavior
Prettier formatting the code

### Actual Behavior
Prettier coaches with the error message
```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'prettier/parser-babel'
Require stack:
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier-plugin-package/lib/index.js
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/common/load-plugins.js
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/index.js
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/cli/index.js
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/bin/prettier.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier-plugin-package/lib/index.js:11:21)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier-plugin-package/lib/index.js',
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/common/load-plugins.js',
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/index.js',
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/cli/index.js',
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/bin/prettier.js'
  ]
}
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'prettier/parser-babel'
Require stack:
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier-plugin-package/lib/index.js
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/common/load-plugins.js
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/index.js
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/cli/index.js
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/bin/prettier.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier-plugin-package/lib/index.js:11:21)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier-plugin-package/lib/index.js',
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/common/load-plugins.js',
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/index.js',
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/cli/index.js',
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/bin/prettier.js'
  ]
}
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'prettier/parser-babel'
Require stack:
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier-plugin-package/lib/index.js
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/common/load-plugins.js
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/index.js
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/cli/index.js
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/bin/prettier.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier-plugin-package/lib/index.js:11:21)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier-plugin-package/lib/index.js',
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/common/load-plugins.js',
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/index.js',
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/cli/index.js',
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/bin/prettier.js'
  ]
}
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'prettier/parser-babel'
Require stack:
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier-plugin-package/lib/index.js
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/common/load-plugins.js
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/index.js
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/cli/index.js
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/bin/prettier.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier-plugin-package/lib/index.js:11:21)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier-plugin-package/lib/index.js',
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/common/load-plugins.js',
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/index.js',
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/cli/index.js',
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/bin/prettier.js'
  ]
}
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'prettier/parser-babel'
Require stack:
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier-plugin-package/lib/index.js
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/common/load-plugins.js
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/index.js
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/cli/index.js
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/bin/prettier.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier-plugin-package/lib/index.js:11:21)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier-plugin-package/lib/index.js',
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/common/load-plugins.js',
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/index.js',
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/cli/index.js',
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/bin/prettier.js'
  ]
}
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'prettier/parser-babel'
Require stack:
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier-plugin-package/lib/index.js
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/common/load-plugins.js
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/index.js
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/cli/index.js
- /root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/bin/prettier.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier-plugin-package/lib/index.js:11:21)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier-plugin-package/lib/index.js',
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/common/load-plugins.js',
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/index.js',
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/src/cli/index.js',
    '/root/.cache/pre-commit/repoq0ap5ups/node_env-system/lib/node_modules/prettier/bin/prettier.js'
  ]
}
```

**Comment by shellscape** [comment] 2020-11-03 15:30
That environment is pretty specific to your machine and setup, require chain, etc, so I'm afraid you'll have to debug it locally on your machine and let us know what the issue is. Most of my projects use this package via lint-staged and I don't have any issues.

**Comment by sindre-nistad** [comment] 2020-11-03 15:46
For context, it works on my machine, but not in the CI pipeline (Azure DevOps).
It also worked fine for a long time, until I upgraded to 1.2.0. Before that, I don't know which version I used.

Also, _.pre-commit-config.yaml_ can be made smaller, and still recreate the issue;

```
default_language_version:
  python: python3.9

repos:
  - repo: https://github.com/prettier/prettier
    rev: 2.1.2
    hooks:
      - id: prettier
        args: [
            "--config=.prettier.config.js",
           "--plugin=prettier-plugin-package",
          ]
        additional_dependencies:
          - prettier-plugin-package@1.2.0
```

Also, pre-commit, is similar to husky, and other tools for managing pre-commit hooks.

I get the same error message with version 1.0.0 through 1.2.0.

Also, the error seem to arise from `const { parsers } = require('prettier/parser-babel')`, as

**Comment by JounQin** [comment] 2021-04-16 01:19
It should be related to duplicate `prettier` versions, because `parser-babel` was formerly named `parser-babylon` in `prettier@1`. It is caused by some `prettier` plugins require `prettier@1` as `dependencies` and have not upgraded to `prettier@2`.

You can try to use `"resolutions": {"prettier": "^2.2.1"}`.

**Comment by shellscape** [comment] 2021-07-27 01:06
Closing as could not reproduce and since there is an apparent workaround for the possible condition causing this issue.

**Closed as completed by shellscape** 2021-07-27 01:06 UTC
Labels: c⁴ ⋅ need more info
